### ISSUE TITLE
When "next" is clicked while "saving...", rationale is not saved for the intented assessment

### ISSUE THREAD

**Issue by GaetReady** [Project-Catalyst/vca-tool#49]
When "next" is clicked while "saving...", rationale may not be saved for the intented assessment.
This may result into rationale not being saved, or being related to the wrong assessment.
Suggested fix : prevent the "next" function to operate while "saving..." is on

**Comment by coire1** [comment]
@jbmattos Check this also in the vue3 version. It's still valid when you click next just before the review is saved.

**Comment by jbmattos** [comment]
addressed on 018b3254beb65767a4c649c5564fd45d9ddc935e
