### ISSUE TITLE
Pagination

### ISSUE THREAD

**Issue by coire1** [Project-Catalyst/vca-tool#51]
Move the [`paginationCurrentPage` logic](https://github.com/Project-Catalyst/vpa-tool/blob/supabase-integration/src/components/SearchList.vue#L85) to a route parameter.

Final goal is to have an address like `http://localhost:5174/assessments/7` and go automatically to page 7.
A new parameter for `page` should be added to the `search` route and propagated to the `SearchList` component.
`changePage()` will trigger the new route and a watcher on the `currentPage` coming from the URL will trigger a new `loadAssessments`.
In this way, coming back from the "Assessment" page can display the old page number.

!!! Please remove Jquery from the project :dagger: Use native js `.scrollIntoView({ behavior: "smooth" })` :

**Comment by coire1** [comment]
In addition to this, move the pagination logic from the store to supabase.
The ideal scenario is to have a `supabase.fetchAssessments(page, size)` method that can be used in the store where `size` is optional with a default value coming from `.env` variable.
In this way if we need pagination for other supabase things, we already have something there.

**Comment by jbmattos** [comment]
> In addition to this, move the pagination logic from the store to supabase. The ideal scenario is to have a `supabase.fetchAssessments(page, size)` method that can be used in the store where `size` is optional with a default value coming from `.env` variable. In this way if we need pagination for other supabase things, we already have something there.

addressed on f125ad6c9425e953bdf237a64e305be78f949a4b
